
######################################################

# Copyright (c) 2003-2020, Ansys, Inc. All rights reserved.  

# Unauthorized use, distribution, or duplication is prohibited.  
# This product is subject to U.S. laws governing export and re-export.  

# For full Legal Notice, see documentation.

######################################################

## This quality assurance (QA) script file tests the photonic elements
## generated using cml-compiler's 'spar_fixed' photonic model

## This is a top level script file that calls multiple sub-scripts
clear;
cd(filedirectory(which(currentscriptname))+'/QA');

### QA description
?QA_description = "Testing:
1. S parameter (amplitude and phase)
2. Group delay (s)
3. Reciprocity, passivity
Conditions:
1. Frequency and time domain simulations
2. All supported polarizations
3. Against source data
4. Against reference data"
;


### Run inidividual subtests
# 1. Frequency domain amplitude, phase, reciprocity and passivity test
feval("spar_fixed_passivity_reciprocity_qa.lsf");

# 2. Comparison with source data
feval("spar_fixed_source_qa.lsf");

# 3. Comparison with reference data
feval("spar_fixed_regression_qa.lsf");

# 4. Time domain test
feval("spar_fixed_time_domain_qa.lsf");

 ### Display the final message in Script prompt
?endl;
if(error_count>0){
?"error_count = " + num2str(error_count);
}
else{
?"All tests passed.";
}pause(2);